name: helpers
description: helpers is a tool that allows you to convert repetitive and tedious statements into easy-to-read and intuitive statements.
version: 1.0.0
homepage: https://github.com/seel-channel/helpers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
